"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import error as components_error
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import order as components_order
from ...models.components import order_input as components_order_input
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional


@dataclasses.dataclass
class CreateOrderRequest:
    request_body: List[components_order_input.OrderInput] = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    callback_url: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'callback_url', 'style': 'form', 'explode': True }})
    r"""The url to call when the order is updated."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateOrderResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    order: Optional[components_order.Order] = dataclasses.field(default=None)
    r"""The order was created successfully."""
    error: Optional[components_error.Error] = dataclasses.field(default=None)
    r"""An unknown error occurred interacting with the API."""
    

