"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import drink as components_drink
from ...models.components import drinktype as components_drinktype
from ...models.components import error as components_error
from ...models.components import httpmetadata as components_httpmetadata
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional


@dataclasses.dataclass
class ListDrinksRequest:
    drink_type: Optional[components_drinktype.DrinkType] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'drinkType', 'style': 'form', 'explode': True }})
    r"""The type of drink to filter by. If not provided all drinks will be returned."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ListDrinksResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    drinks: Optional[List[components_drink.Drink]] = dataclasses.field(default=None)
    r"""A list of drinks."""
    error: Optional[components_error.Error] = dataclasses.field(default=None)
    r"""An unknown error occurred interacting with the API."""
    

