"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .schemeclientcredentials import SchemeClientCredentials
from typing import Optional


@dataclasses.dataclass
class Security:
    api_key: Optional[str] = dataclasses.field(default=None, metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'Authorization' }})
    client_credentials: Optional[SchemeClientCredentials] = dataclasses.field(default=None, metadata={'security': { 'scheme': True, 'type': 'oauth2', 'sub_type': 'client_credentials' }})
    

