"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .stockupdate import StockUpdateRequestBody, StockUpdateRequestBodyTypedDict, StockUpdateResponse, StockUpdateResponseTypedDict

__all__ = ["StockUpdateRequestBody", "StockUpdateRequestBodyTypedDict", "StockUpdateResponse", "StockUpdateResponseTypedDict"]
