"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from speakeasy_bar_py.models.components import (
    drink_input as components_drink_input,
    error as components_error,
    httpmetadata as components_httpmetadata,
    ingredient as components_ingredient,
)
from speakeasy_bar_py.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StockUpdateRequestBodyTypedDict(TypedDict):
    drink: NotRequired[components_drink_input.DrinkInputTypedDict]
    ingredient: NotRequired[components_ingredient.IngredientTypedDict]


class StockUpdateRequestBody(BaseModel):
    drink: Optional[components_drink_input.DrinkInput] = None

    ingredient: Optional[components_ingredient.Ingredient] = None


class StockUpdateResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    error: NotRequired[components_error.ErrorTypedDict]
    r"""An unknown error occurred interacting with the API."""


class StockUpdateResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    error: Optional[components_error.Error] = None
    r"""An unknown error occurred interacting with the API."""
