"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from speakeasy_bar_py.models.components import (
    error as components_error,
    httpmetadata as components_httpmetadata,
)
from speakeasy_bar_py.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AuthenticateRequestBodyTypedDict(TypedDict):
    username: NotRequired[str]
    password: NotRequired[str]


class AuthenticateRequestBody(BaseModel):
    username: Optional[str] = None

    password: Optional[str] = None


class AuthenticateResponseBodyTypedDict(TypedDict):
    r"""The api key to use for authenticated endpoints."""

    token: NotRequired[str]


class AuthenticateResponseBody(BaseModel):
    r"""The api key to use for authenticated endpoints."""

    token: Optional[str] = None


class AuthenticateResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    object: NotRequired[AuthenticateResponseBodyTypedDict]
    r"""The api key to use for authenticated endpoints."""
    error: NotRequired[components_error.ErrorTypedDict]
    r"""An unknown error occurred interacting with the API."""


class AuthenticateResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    object: Optional[AuthenticateResponseBody] = None
    r"""The api key to use for authenticated endpoints."""

    error: Optional[components_error.Error] = None
    r"""An unknown error occurred interacting with the API."""
