"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from speakeasy_bar_py.models.components import (
    error as components_error,
    httpmetadata as components_httpmetadata,
)
from speakeasy_bar_py.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Webhook(str, Enum):
    STOCK_UPDATE = "stockUpdate"


class RequestBodyTypedDict(TypedDict):
    url: NotRequired[str]
    webhook: NotRequired[Webhook]


class RequestBody(BaseModel):
    url: Optional[str] = None

    webhook: Optional[Webhook] = None


class SubscribeToWebhooksResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    error: NotRequired[components_error.ErrorTypedDict]
    r"""An unknown error occurred interacting with the API."""


class SubscribeToWebhooksResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    error: Optional[components_error.Error] = None
    r"""An unknown error occurred interacting with the API."""
