workflowVersion: 1.0.0
sources:
    bar-openapi:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-bar-test/speakeasy-bar-test/bar-api
targets:
    my-first-target:
        target: python
        source: bar-openapi
