workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    bar-openapi:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-bar-test/speakeasy-bar-test/bar-api
targets:
    my-first-target:
        target: python
        source: bar-openapi
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/speakeasy-bar-test/speakeasy-bar-test/code-samples-python-my-first-target
