"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from speakeasy_bar_py.models.components import (
    error as components_error,
    httpmetadata as components_httpmetadata,
    order_input as components_order_input,
)
from speakeasy_bar_py.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateOrderOrderUpdateResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    error: NotRequired[components_error.ErrorTypedDict]
    r"""An unknown error occurred interacting with the API."""


class CreateOrderOrderUpdateResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    error: Optional[components_error.Error] = None
    r"""An unknown error occurred interacting with the API."""


class CreateOrderOrderUpdateRequestBodyTypedDict(TypedDict):
    order: NotRequired[components_order_input.OrderInputTypedDict]
    r"""An order for a drink or ingredient."""


class CreateOrderOrderUpdateRequestBody(BaseModel):
    order: Optional[components_order_input.OrderInput] = None
    r"""An order for a drink or ingredient."""
