"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from speakeasy_bar_py import utils
from speakeasy_bar_py.types import BaseModel
from typing import Any, Dict, Optional


class APIErrorData(BaseModel):
    code: Optional[str] = None

    message: Optional[str] = None

    details: Optional[Dict[str, Any]] = None


class APIError(Exception):
    r"""An error occurred interacting with the API."""

    data: APIErrorData

    def __init__(self, data: APIErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, APIErrorData)
