"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from speakeasy_bar_py.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ErrorTypedDict(TypedDict):
    r"""An unknown error occurred interacting with the API."""

    code: NotRequired[str]
    message: NotRequired[str]


class Error(BaseModel):
    r"""An unknown error occurred interacting with the API."""

    code: Optional[str] = None

    message: Optional[str] = None
