"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from speakeasy_bar_py.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ErrorTypedDict(TypedDict):
    code: NotRequired[str]
    message: NotRequired[str]
    

class Error(BaseModel):
    code: Optional[str] = None
    message: Optional[str] = None
    
