"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .ingredienttype import IngredientType
import pydantic
from speakeasy_bar_py.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class IngredientTypedDict(TypedDict):
    name: str
    r"""The name of the ingredient."""
    type: IngredientType
    r"""The type of ingredient."""
    product_code: NotRequired[str]
    r"""The product code of the ingredient, only available when authenticated."""
    

class Ingredient(BaseModel):
    name: str
    r"""The name of the ingredient."""
    type: IngredientType
    r"""The type of ingredient."""
    product_code: Annotated[Optional[str], pydantic.Field(alias="productCode")] = None
    r"""The product code of the ingredient, only available when authenticated."""
    
