"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .ordertype import OrderType
import pydantic
from speakeasy_bar_py.types import BaseModel
from typing import TypedDict
from typing_extensions import Annotated


class OrderInputTypedDict(TypedDict):
    r"""An order for a drink or ingredient."""
    
    type: OrderType
    r"""The type of order."""
    product_code: str
    r"""The product code of the drink or ingredient."""
    quantity: int
    r"""The number of units of the drink or ingredient to order."""
    

class OrderInput(BaseModel):
    r"""An order for a drink or ingredient."""
    
    type: OrderType
    r"""The type of order."""
    product_code: Annotated[str, pydantic.Field(alias="productCode")]
    r"""The product code of the drink or ingredient."""
    quantity: int
    r"""The number of units of the drink or ingredient to order."""
    
